server:
  port: 8082
  servlet:
    context-path: /customer-service

spring:
  application:
    name: customer-service

  datasource:
    url: jdbc:mariadb://localhost:3306/customer_db
    username: root
    password: 123456
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
